name: wf-cd-delopyment
on:
  push:
    branches:
      - develop

jobs:
  build-development-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Website for deployment
        runs: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
      - name: Upload Artifacts to GH cloud
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "build-artifact-development"

  deploy-development-job:
    needs: build-development-job
    environmnet: "development-env"
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Development Artifacts
        uses: actions/deploy-pages@v4
        with: 
          artifact_name: "build-artifact-development"
          token: ${{github.token}}